/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#6f7a72",
        "surface-tint": "#026c4a",
        "on-background": "#051f24",
        "inverse-primary": "#82d8ae",
        "on-tertiary-container": "#f8fff4",
        "on-tertiary": "#ffffff",
        "surface-dim": "#c4dfe5",
        "on-secondary-container": "#326e68",
        "on-primary-container": "#f4fff6",
        "secondary": "#2b6862",
        "secondary-container": "#b1eee7",
        "surface-container-high": "#d2edf3",
        "on-secondary-fixed-variant": "#0a504b",
        "outline-variant": "#bec9c1",
        "on-primary-fixed-variant": "#005237",
        "primary-fixed-dim": "#82d8ae",
        "background": "#effcff",
        "tertiary-fixed-dim": "#a1d2a8",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#00210b",
        "on-secondary-fixed": "#00201e",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#23502f",
        "surface-container": "#d8f3f9",
        "inverse-surface": "#1c3439",
        "primary-fixed": "#9df4c9",
        "on-secondary": "#ffffff",
        "surface-container-low": "#def8ff",
        "on-primary-fixed": "#002114",
        "surface": "#effcff",
        "tertiary": "#396643",
        "surface-bright": "#effcff",
        "primary-container": "#2a835f",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#96d2cb",
        "on-error-container": "#93000a",
        "surface-variant": "#cde7ee",
        "on-surface-variant": "#3f4943",
        "secondary-fixed": "#b1eee7",
        "inverse-on-surface": "#dbf5fc",
        "tertiary-fixed": "#bdefc3",
        "tertiary-container": "#517f5a",
        "surface-container-highest": "#cde7ee",
        "error": "#ba1a1a",
        "primary": "#006948",
        "error-container": "#ffdad6",
        "on-surface": "#051f24"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-2xl": "3rem",
        "space-lg": "1.5rem",
        "container-max": "72rem",
        "space-xs": "0.5rem",
        "space-xl": "2rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
        "space-2xs": "0.25rem",
        "space-sm": "0.75rem",
        "space-3xl": "4rem",
        "gutter-desktop": "1.5rem"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "caption": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "caption": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
